### ISSUE TITLE
FILLING THE DELIVERABLES REPORT

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#101]
There is only couple hours left for submission deadline. But right now, only Berke, Cem and I are the only ones that fill their personal contributions. Everyone should put their part as soon as possible.

**Comment by cemkaya-mpi** [comment]
We also need to create a documentation of the API and a guide to use our app!

**Comment by cemkaya-mpi** [comment]
Report was submitted by our communicator. Closing the issue.
