### ISSUE TITLE
Filling Wiki Page

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#104]
Our personal efforts, meeting notes, milestone 2 report are missing on our wiki page. We have to fill it by tomorrow evening.

**Comment by yunus-topal** [comment]
I filled backend part of the milestone report.

**Comment by 4teko7** [comment]
I filled AWS, Docker parts in both "Evaluation of Tools and Processes Used" and "Code and Deployment of Practice App" parts. Filled Responsibility Matrix, Wrote some other parts.

**Comment by gktpmuhammed** [comment]
I prepared roadmap on Project Libre. In milestone report I filled Executive Summary part.

**Comment by emrahdgn** [comment]
Milestone 2 report also uploaded.

**Comment by gktpmuhammed** [comment]
Milestone report uploaded. I am closing this issue.
