### ISSUE TITLE
Determining the weekly meeting schedule.

### ISSUE THREAD

**Issue by BerkeArgin** [bounswe/2021SpringGroup1#110]
[Here's](https://doodle.com/poll/k8wyigceudtfs4tt?utm_source=poll&utm_medium=link) the doodle for the weekly meeting schedule. Please select all of the time slots that suit you ASAP. You can select a time slot both as primary or secondary choice.

**Comment by emrahdgn** [comment]
It may be a good idea to choose suitable times on a Thursday or Friday.
