### ISSUE TITLE
Determining the Backend Framework

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#113]
We should decide on the backend framework for our project ASAP.  We can use [this discussion thread](https://github.com/bounswe/2021SpringGroup1/discussions/112) to exchange ideas and suggestions. 
Suggested frameworks are:
- [Django](https://www.djangoproject.com/)
- [Spring boot](https://spring.io/projects/spring-boot)

[Here ](https://javasterling.com/spring-boot/spring-boot-vs-django/)is an article that compares these two frameworks.Also, any other framework suggestions are appreciated. [Here ](https://blog.back4app.com/backend-frameworks/)is another article on some popular frameworks.

**Comment by emrahdgn** [comment]
Team agreed on Django framework. Therefore i am closing this issue.
