### ISSUE TITLE
Determining the Deployment Service

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#114]
We should decide to the deployment service for our project as soon as possible because we will present our first prototype at 16 November. 

Possible deployment service provider options are:
- [Amazon Web Services (AWS)](https://aws.amazon.com)
- [Google Cloud Platform (GCP)](https://cloud.google.com)
- [Microsoft Azure ](https://azure.microsoft.com)

Customer strongly recommends choosing Microsoft Azure as other providers may cause unexpected problems.
Also Heroku can not be selected.

There is a very detailed [article](https://www.datamation.com/cloud/aws-vs-azure-vs-google-cloud/) comparing this deployment services.

Please share your ideas and preferences in the comments.

**Comment by yunus-topal** [comment]
We decided to use aws as deployment service in the meeting.
