### ISSUE TITLE
Determining Front-end Frameworks for Web and Android app

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#115]
We should decide to the Front-end frameworks for our project as soon as possible because we will present our first prototype at 16 November. Front-end must be done for Android and Web platforms.

Some of the possible Front-end framework options are:

- [React](https://reactjs.org)
- [Angular](https://angular.io)
- [Kotlin](https://developer.android.com/kotlin)

The customer does not want cross-platforms frameworks. Flutter framework can not be selected.

Please share your ideas and preferences in the comments.

**Comment by yunus-topal** [comment]
For android app, we decided to use React Native. We can close this issue after deciding web framework.

**Comment by MrLebowski42** [comment]
Our decisions on the frameworks are as below:
* Backend Framework: Django
* Web Frontend : React 
* Mobile : React Native
​
I am closing this issue until an possible update.
