### ISSUE TITLE
Deciding feature to implement for Milestone 1

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#119]
We divided into groups and now it is time to decide which features will be implemented. Mobile and web version of our app should be consisted. And also, backend team shouldn't waste time on features that is not needed at the moment.

**Comment by MrLebowski42** [comment]
For the features that we are planning to implement for the Milestone 1, I've added the simple UI design sketches that we created during [Meeting 3](url). I've added the page in our wiki. You can check the page [here](https://github.com/bounswe/2021SpringGroup1/wiki/Sample-UI-Design-for-Milestone-1).

**Comment by MrLebowski42** [comment]
Based on the [Meeting 3](url) and [Meeting 4](url) discussions, I've created a [page](https://github.com/bounswe/2021SpringGroup1/wiki/Milestone-1-Requirements) for the chosen requirements that we are aiming to fulfill. There is also a [basic UI design sketch](https://github.com/bounswe/2021SpringGroup1/wiki/Sample-UI-Design-for-Milestone-1) ( that will probably need some refinement) so we can close this issue for now.
