### ISSUE TITLE
Learning React for Frontend Development

### ISSUE THREAD

**Issue by gktpmuhammed** [bounswe/2021SpringGroup1#120]
We decided to use React for Frontend development.  [This](https://www.youtube.com/watch?v=Dorf8i6lCuk) is the tutorial I found. 
official react website : [https://tr.reactjs.org](https://tr.reactjs.org)

If you know better tutorials please share with us here.

**Comment by emiroztoprak** [comment]
I have also started learning React for our project. Thanks for the tutorials, and I also found some Youtube channels that give a quick tutorial about React and other similar frameworks. I'll leave the links below:  

- [An introductory tutorial](https://www.youtube.com/playlist?list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3)
- [A list of projects in React.js](https://www.youtube.com/watch?v=XuFDcZABiDQ&list=PLillGF-RfqbY3c2r0htQyVbDJJoBFE6Rb)

**Comment by gktpmuhammed** [comment]
I think everyone learned react. So I am closing this issue.
