### ISSUE TITLE
Deciding Project Name and Designing Project Logo

### ISSUE THREAD

**Issue by orkana** [bounswe/2021SpringGroup1#121]
We should find a name for the project and design its logo.

**Comment by MrLebowski42** [comment]
There is an existing [discussion thread](https://github.com/bounswe/2021SpringGroup1/discussions/111 ) for this. We can discuss ideas in there.

**Comment by gktpmuhammed** [comment]
I think we can close this issue now. Our application name is ProtoPost and the logo for our app is [here.](https://allisonpastordesigns.com/wp-content/uploads/2018/09/pp-logo-blue-03.png)
