### ISSUE TITLE
Android Team: Milestone 1 preliminary meeting.

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#125]
We had decided on the core features and requirements that we are going to implement for Milestone 1. We also have a basic UI design sketch and discussed backend API. Now, each team should be able to figure out some necessary tasks of their own and plan towards the implementation. After team meetings, three teams should come together to create a solid project plan based on these team tasks and workshare.

**Comment by yunus-topal** [comment]
We didn't have a meeting for M1 but we implemented most of the features. But we need to get together before Milestone 2 and make our plans accordingly.
