### ISSUE TITLE
Frontend-Web tools.

### ISSUE THREAD

**Issue by 4teko7** [bounswe/2021SpringGroup1#134]
There are many libraries that we can use. For example,
-For API request to backend we can use https://www.npmjs.com/package/axios. It is very fast and popular npm package.
-Navigation is very important for frontend applications. Here is the ReactJS official navigation. Please check it: https://reactnavigation.org/
-Hooks are very important in modern react and react native applications. We must know it because we will write functional components. Here is the official react hook documentation: https://reactjs.org/docs/hooks-intro.html
-For state management, we should use Redux-Thunk: https://github.com/reduxjs/redux-thunk. It is very popular for both in Web and Mobile applications.

Please indicate other important tools for ReactJS.

**Comment by emiroztoprak** [comment]
Thanks for the guide. I had some knowledge about most of them but I didn't know much about Redux-Thunk. I will do some research and learn more about it.
