### ISSUE TITLE
Writing Unit-Tests for Backend Functions

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#135]
There is a need to write unit tests for functions in backend. We cannot deliver the app without unit testing.
We should start writing without accumulating too many functions.

**Comment by emrahdgn** [comment]
Test functions about Community creating and listing,  creating and listing post templates, getting home feed are implemented. 
The remaining functions should be added as soon as possible.

**Comment by MrLebowski42** [comment]
We have written the necessary unit tests so I'm closing this issue.
