### ISSUE TITLE
Implementing API calls for mobile 

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#142]
We have almost every feature except post creation right now. But we are using dummy inputs for everything. We need to learn how to make Requests to our backend api and replace dummy inputs with real results.

**Comment by MrLebowski42** [comment]
API calls for creating communities, posts andost templates are done. We can set up a small meeting to discuss connecting the frontend to our entrypoints and endpoints.

**Comment by yunus-topal** [comment]
We added api calls to necessary places and showed what we have during the demo. Unfortuantely, there was an issue related to cookies and we were not able to show everything we did. But still, those feature are implemented and they will work after our backend team fixes cookie issue.
