### ISSUE TITLE
Creating Feed Page

### ISSUE THREAD

**Issue by gktpmuhammed** [bounswe/2021SpringGroup1#147]
We will create feed page for users. Users can see posts of their communities in this page.

**Comment by emiroztoprak** [comment]
We used Card objects in react-bootstrap library. I think it worked well with our initial sketch designs. We are open for feedback from other teammates.

**Comment by gktpmuhammed** [comment]
@emiroztoprak and I designed the feed page. We used Card objects in react-bootstrap. We added a sidebar to the page. You can go to other pages by using this sidebar. It was commited and pushed the Web_ReactJS branch. You can find pull request [here.](https://github.com/bounswe/2021SpringGroup1/pull/144)
