### ISSUE TITLE
Creating Templates for Personel Efforts

### ISSUE THREAD

**Issue by gktpmuhammed** [bounswe/2021SpringGroup1#16]
I think we need a template for personel efforts page. With this template our page design will be better. 

So, we can search past years groups personel effort page templates and create ours.

**Comment by cemkaya-mpi** [comment]
How about [this?](https://pastebin.com/0UrwEuzM) This is a template for my current page.

**Comment by cemkaya-mpi** [comment]
Updated link [here](https://u.pcloud.link/publink/show?code=XZ8FXsXZadOSdlY0nkY1SiQVaTu3lH0rJ2mV) for those of you who  couldn't access the file.

**Comment by cemkaya-mpi** [comment]
Please remove yourselves from assignees once you're done updating your personal pages. The OP @gktpmuhammed can close this issue once he is the only one remaining.

**Comment by cemkaya-mpi** [comment]
Has everyone updated their pages?  Please remove yourselves from the assignees after, so we know when to close this issue.

**Comment by cemkaya-mpi** [comment]
I believe everyone has updated their pages by now. I am closing this issue.
