### ISSUE TITLE
Deploying the Backend API service to AWS

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#160]
Backend functions are all mostly implemented so we should deploy our backend service and database to a AWS instance so that Frontend won't require local setups to integrate API calls.

**Comment by emrahdgn** [comment]
After hours of trying, we solved the little bug and managed to deploy it.
You can now access the API service of our application at http://54.217.117.68:8000/

You can access the [Swagger Documentation](http://54.217.117.68:8000/api/schema/swagger-ui/) by clicking link.
