### ISSUE TITLE
BUG: user_subscription call producing error

### ISSUE THREAD

**Issue by elxif** [bounswe/2021SpringGroup1#165]
When I try to check if my user is subscribed to a community using the [api call](http://54.217.117.68:8000/api/v1/protopost/communities/1/user_subscription
), I get Internal Server Error.

Both the GET and PUT methods produce errors.

If I use the id of a nonexistent community, no errors occur.

**Comment by MrLebowski42** [comment]
Fixed it manually on the server and will be commiting the fix soon. It should be working now.
