### ISSUE TITLE
Preparing the Milestone 1 group report.

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#177]
We had discussed the work share for the group report in [Meeting 3](https://github.com/bounswe/2021SpringGroup1/wiki/Meeting-Notes-16-(18.11.2021)). Now we need to create some additional issues and prepare our related sections in subgroups then join them ASAP. Google Document link is pinned on our Discord server.

**Comment by gktpmuhammed** [comment]
I have updated Frontend part for RAM and Project Plan sections. If you see anything missing, please add it @4teko7 and @emiroztoprak .

**Comment by yunus-topal** [comment]
I've filled Mobile parts for Evaluation of the Deliverables, Evaluation of Tools, Moving Forward, Roadmap, Project Plan and RAM in our Milestone report

**Comment by gktpmuhammed** [comment]
I've filled Web Frontend parts for Evaluation of the Status of Deliverables, Moving Forward, Current Status and Evaluation of Tools and Processes Used in Milestone report.

**Comment by gktpmuhammed** [comment]
I have updated project plan and put screenshots to Milestone report.

**Comment by MrLebowski42** [comment]
Milestone 1 report is complete. I'm closing this issue.
