### ISSUE TITLE
Writing Evaluation of Tools and Processes section of the Milestone 1 Report.

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#180]
We need to fill in the Evaluation of Tools and Processes section ASAP. Each subgroup can add the parts of their own tools.

**Comment by MrLebowski42** [comment]
I've added the descriptions and evaluations for Django, Django REST framework and Docker for the backend.

**Comment by yunus-topal** [comment]
I've added evaluations for React-Native, React Navigation, Expo Go, React Axios for Android part.

**Comment by gktpmuhammed** [comment]
I've added evaluations for React hooks, React Axios and React Redux for Web Frontend part.

**Comment by MrLebowski42** [comment]
Milestone 1 report is complete. I'm closing this issue.
