### ISSUE TITLE
Missing features for Android 

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#183]
Unfortunately, we couldn't finish 3 features for Milestone 1 and they are:
Create Post Template
Create Post
Create community

We need to finish these and work on features for next Milestone.

**Comment by yunus-topal** [comment]
@orkana how is it going? I couldn't see your branch on our repo. Can you share your progress with a branch so maybe we can help  and finish together?

**Comment by yunus-topal** [comment]
I implemented create community feature on mobile. We are working on other 2 functionalities.

**Comment by elxif** [comment]
We decided that I should implement the create post feature. v1 is implemented and pushed to the mobile-elif branch right now.

**Comment by yunus-topal** [comment]
I implemented create post template feature and made a pull request.

**Comment by yunus-topal** [comment]
I implemented create post features
