### ISSUE TITLE
Deciding on the features to implement for Milestone 2

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#185]
We need to decide on some additional features that we are going to implement before the 2. Customer Demo. Our initial ideas are:

- Adding support for Location data field for the posts.
- Adding some search and filtering capability for posts and communities.
- Improving on the UI design and refining backend API
Note that our first priority is to have a functioning app so we should first focus on integrating the current features correctly.

**Comment by yunus-topal** [comment]
we might need a search feature for communities. Because theoretically there can be hundreds of communities and users should be able to search them efficiently.

**Comment by yunus-topal** [comment]
We finished customer demo 2.
