### ISSUE TITLE
search_communities endpoint bug

### ISSUE THREAD

**Issue by emiroztoprak** [bounswe/2021SpringGroup1#198]
In the backend, search_communities API call returns a list of the matching communities, but all the results have the field isJoined:false. This can cause further problems in the front-end. I also tried it in Swagger-ui but I encountered the same bug. Any ideas what could be causing it?

**Comment by MrLebowski42** [comment]
This was due to a small mistake on passing proper contexts to serializers . I created a PR #200 that fixes this bug and after deployment of this code we can close this issue.

**Comment by MrLebowski42** [comment]
Bug patches are deployed so I'm closing this issue.
