### ISSUE TITLE
Adding project name and logo on wiki page

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#202]
We are now using name ProtoPost and have our [initial logo](https://allisonpastordesigns.com/wp-content/uploads/2018/09/pp-logo-blue-03.png) set. We should add them to our homepage and wiki for the appropiate presentation of our project. I'm assigning this task to Orkan for now.

**Comment by gktpmuhammed** [comment]
I have added the project name and logo to the wiki page. You can access the wiki page from [here.](https://github.com/bounswe/2021SpringGroup1/wiki)
I am closing this issue.
