### ISSUE TITLE
Planning on implementing filtering feature

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#217]
We need to plan on creating powerful query mechanisms to provide robust post searching and filtering functionality to our app. Currently, DataField objects holds arbitrary JSON as content. Since MySQL does not support much flexibity when it comes down to polymorphism, we may be stuck with this approach. #193  However, if we migrate to MongoDB there will be more flexible models as it's a schema-less DBMS. 

- We need to come up with some query methods for each types of data fields
- We should write functions to our API that enable retrieving query methods for a specific post template .
- We also need to write a function that will take some conditions and returns a list of post with respect to these.

If we stick with MySQL:
- We need to find a way to [filter and process JSON data](https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/fields/#querying-jsonfield) in an efficient way.
- We also need to write some custom validation methods for different data field types.

If we decide to continue with [MongoDB](https://www.mongodb.com/try):
- Learn on MongoDB and its usage
- We need to re-write DataField model and introduce additional classes.
- Migrate the current models to MongoDB

**Comment by emrahdgn** [comment]
Only 6 days left until the final presentation. Therefore, changing the database can cause errors and can take several days to resolve. Therefore, I think we should continue with the MySQL database.

**Comment by MrLebowski42** [comment]
We've implemented this feature so I'm closing this issue.
