### ISSUE TITLE
Milestone 2 Group Report

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#226]
We need to write a report for milestone 2. Due date is 18 December.

**Comment by gktpmuhammed** [comment]
I added project status for Frontend. I have added some tasks to RAM. I have colored requirements based on their completion status. This part needs a review from group members. I have added tasks in tabular format also. I added Material UI in the Evaluation of Tools and Processes Used part. I have added deployed frontend link to the List and Status of Deliverables part.

**Comment by MrLebowski42** [comment]
I wrote general and backend related parts of the project status section in executive summary. We will also be filling in the API documentation section ASAP. Since we set up a swagger page, this won't be much of a trouble.

**Comment by MrLebowski42** [comment]
I also added API Endpoint section, providing link to both API documentation and Postman collection while adding a short guide on how to use these.

**Comment by gktpmuhammed** [comment]
I also wrote core functionalities for frontend. I have updated the project plan in the project libre.

**Comment by yunus-topal** [comment]
I wrote project status, moving forward, project plan and roadmap for mobile. Also, i add screenshots from mobile app for user interface part.

**Comment by emrahdgn** [comment]
Milestone Group Report was submitted at 17 December. Therefore i am closing this issue.
