### ISSUE TITLE
Adding end-point definitions to Swagger documentation

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#227]
Although we have prepared a good documentation for the backend endpoints, we should also write the definitions of these endpoints. In order to do this, we need to make the necessary additions to our code.

**Comment by MrLebowski42** [comment]
Yes, I think that Swagger page is the best way of documentation for our API. We should add some small descriptions and make some organizations then we'll be good to go.

**Comment by MrLebowski42** [comment]
PRs #230 and #229 have been merged and now documentation is complete. I'm closing this issue now.
