### ISSUE TITLE
Deleting junk files and removing unnecessary imports from Backend

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#228]
There are some junk files such as home.py file that we actively use before starting to use Django-Rest Framework. 
Also there are many unnecessary imports. 
For clean coding we have to remove them.

**Comment by MrLebowski42** [comment]
I agree as I also mentioned some commented code in #195. We can remove these files and comments as they are trackable in our commits if we want to access to them later on.
