### ISSUE TITLE
Implementing advanced filtering feature on API

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#232]
As the backend team, we done considerable amount of research on implementing a custom, dynamic filtering feature for our application. We now sketched the structure for implementation and ready to code. 
Implementation has two aspects:

- Implementing core function that is capable of handling arbitrary filtering functions and applying them to the JSON content held by posts.
- Determining necessary query functions and implementing them.
- Organizing and documenting these query functions.

I've implemented most of the core function as well as added some filtering funtions for location and number fields. #236

**Comment by emrahdgn** [comment]
We decided with the Frontend teams that there will be 4 options for the string based advanced search.
1) `<field name>_endsWith` : strings end with the given pattern
2) `<field name>_startsWith` : strings start with the given pattern
3) `<field name>_contains` : strings contains the given pattern
4) `<field name>_equal`: strings equals to the given pattern

**Comment by MrLebowski42** [comment]
We have added necessary endpoints so I'm closing this issue.
