### ISSUE TITLE
Adding query functions to the FilterPosts endpoint

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#234]
Core functionality for the filtering endpoint is nearly done. We should now focus on determining and adding query functions for the data fields. 
Existing ones are:

- Filtering locations based on a lattitute and longtitute point with radius. (`<field_name>_near`)
- Filtering number fields based on ordering. (`<field_name>_gt`, `<field_name>_eq`, `<field_name>_lt`)

These query functions are implemented as lambda functions and taken dynamically from the GET parameters. You can comment your suggestions and/or contributions to this issue or create a new one with adding a link to this issue.

**Comment by emrahdgn** [comment]
Filtering String fields can be based on substring parts: (`<field_name>_eq`, `<field_name>_st`, `<field_name>_en`)
`<field_name>_eq` : equals to the given string
`<field_name>_st` : starts with the given string
`<field_name>_en` : ends with the given string

**Comment by emrahdgn** [comment]
Related Branch was merged. A lot of manual testing was done on the Frontend as well.
Therefore, I am closing this issue.
