### ISSUE TITLE
Populating the database

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#259]
We should populate the database with a good amount of realistic posts. To achieve this, we need website to be deployed.

**Comment by emrahdgn** [comment]
I think this dataset can also be used for Backend tests. I think it would be beneficial to start filling as soon as possible.

**Comment by yunus-topal** [comment]
Before the final demo, we will populate the database.

**Comment by 4teko7** [comment]
The information of database should make sense. They should contain the real values to present a good website in final demo

**Comment by MrLebowski42** [comment]
We added 100 post entries to the deployed database. I'm closing this issue as we will be taking the database dump.
