### ISSUE TITLE
Location input in post creation

### ISSUE THREAD

**Issue by elxif** [bounswe/2021SpringGroup1#271]
Right now, the location data isn't being added in post creation in mobile. We should add it before the customer presentation.

**Comment by yunus-topal** [comment]
Location is crucial for post creation. Beside that, it seems like the state does not update immediately when user clicks on a post template in create post screen. So they have to click twice to a template to use it. This is not a fatal error but an annoying bug. We can work on that as well.

**Comment by yunus-topal** [comment]
We added location creation feature to our mobile application.
