### ISSUE TITLE
Writing the Final Milestone report

### ISSUE THREAD

**Issue by BerkeArgin** [bounswe/2021SpringGroup1#290]
Final milestone report must be finished by tomorrow and we need to update the parts:

-  RAM
-  Adding final release notes
- Final project evaluation

Feel free to add some parts that I've missed by now or comment your contributions.

**Comment by MrLebowski42** [comment]
I added the Backend part for the Implementation of Core Functionalites part and will update the Postman collection for our API tomorrow

**Comment by BerkeArgin** [comment]
We have finished the Milestone report so I'm closing this issue.
