### ISSUE TITLE
Filling Summary of the Work Done

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#40]
Everyone should fill their part on Milestone Report section 5: Summary of Work Done.
You can comment on this issue if you finished your part. Last one should close the issue.

**Comment by cemkaya-mpi** [comment]
Done.

**Comment by MrLebowski42** [comment]
Done.

**Comment by yunus-topal** [comment]
Done.

**Comment by LehabuL** [comment]
Done.

**Comment by yunus-topal** [comment]
done.

**Comment by gktpmuhammed** [comment]
Done.

**Comment by emiroztoprak** [comment]
Done.

**Comment by emrahdgn** [comment]
Done.

**Comment by 4teko7** [comment]
Already Done.

**Comment by yunus-topal** [comment]
Everyone filled their part and we submitted our report.
