### ISSUE TITLE
New Labels

### ISSUE THREAD

**Issue by gktpmuhammed** [bounswe/2021SpringGroup1#5]
Is there any idea about labels? Are the current labels enough?

**Comment by LehabuL** [comment]
We can add as the project proceeds.

**Comment by yunus-topal** [comment]
I added a new label: "Urgent" for urgent tasks.

**Comment by gktpmuhammed** [comment]
I have added Platform based labels: Android, Frontend and Backend.

**Comment by yunus-topal** [comment]
since final demo is over, we will not need new labels anymore.
