### ISSUE TITLE
Putting all features together

### ISSUE THREAD

**Issue by cemkaya-mpi** [bounswe/2021SpringGroup1#62]
Now that we have features such as login, posts, communities and so on, we must put all the features together. This effort will continue in the branch 'MainApp'. Everyone is welcome to assign themselves and join the effort.

**Comment by cemkaya-mpi** [comment]
We should add a login page to the mainapp directory asap. Seems we have forgotten to do so yesterday.

**Comment by MrLebowski42** [comment]
There is a login page for mainapp which @yunus-topal created in our app routes, but we should make some changes on its functionality and tweak on its html template to improve visuals.

**Comment by cemkaya-mpi** [comment]
Yes, I am aware, but I think we should delete the legacy folder/routes and create necessary ones for the "mainapp" to be consistent. For example, any function called from my 'community' folder will fail due to the changes in database since it was created. Mixing and matching functions and pages from different projects might not be a good idea. I've already pushed login.html to the MainApp branch.

**Comment by MrLebowski42** [comment]
Good point. Okay, then we'll have to integrate the view functions of login to our mainapp.

**Comment by yunus-topal** [comment]
We can get rid of post2 and its models without a problem i think. But right now we are using person apps model in mainapp and login feature is done by login app so we need to take care of them first. 

We could just copy and paste Person model into mainapp.models file but then @4teko7 's work will be lost. Maybe he can rearrange that part?

Dealing with login feature is also simple.  Inside cmpe352/urls.py file, we can chage mainapp path to '' from 'mainapp' so we can get into mainapp from base url. Of course, after doing this, we need to change urls inside mainapp/routes.py. We can add mainapp/ all of them to not mess up routing inside views.py and html files.

**Comment by MrLebowski42** [comment]
We are almost done putting all of the features together. However, we still need several more third party API contributions.
