### ISSUE TITLE
Adding like feature and personal api call to MainApp branch

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#64]
Creating dummy posts and like features are missing in our MainApp. I will add them and update our MainApp branch soon.

**Comment by MrLebowski42** [comment]
Can you notify me when you are done so we can discuss merging our works?

**Comment by yunus-topal** [comment]
I will. Liking feature will effect several functions so it might take a while to make sure everything is working correctly.

**Comment by yunus-topal** [comment]
Unfortunately, i was afraid that i could mess up some stuff in our viewpost/createpost functions so i didn't implement like feature in our MainApp branch. But in yunus branch, like feature exists and working fine so i am not gonna delete that branch for now. Also, dummy post creating seemed a bit pointless to me and i changed that to cat facts! Now when you go to the registration page, you will be greeted by random cat fact.
