### ISSUE TITLE
login html page in MainApp

### ISSUE THREAD

**Issue by cemkaya-mpi** [bounswe/2021SpringGroup1#67]
I've created an html for the login page in the mainapp templates folder. Could someone please assign themselves and write the routes and backend functions to integrate it?

**Comment by cemkaya-mpi** [comment]
It would be nice to have a logout feature too.

**Comment by yunus-topal** [comment]
I put login page in localhost url and i will add logout feature in main page soon

**Comment by yunus-topal** [comment]
I put logout button aswell. You can check mainapp to make sure everything alright and close this issue

**Comment by cemkaya-mpi** [comment]
Seems to be working for me. We can close this issue.
