### ISSUE TITLE
Writing the frontend for createPost page

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#68]

**Comment by MrLebowski42** [comment]
I will now look at the frontend for post creation. This includes viewing post templates and creating a post based on a template.

**Comment by yunus-topal** [comment]
Then i will close #66 and then i might write an html file for createPerson.

**Comment by MrLebowski42** [comment]
I created a page for our app that enables posting. While it requires some tweaks now and then, I think we can close this issue for now.
