### ISSUE TITLE
Creating html file for leaving a community

### ISSUE THREAD

**Issue by gktpmuhammed** [bounswe/2021SpringGroup1#70]

**Comment by cemkaya-mpi** [comment]
We already have this as a button in the 'view community' page.

**Comment by gktpmuhammed** [comment]
It is not working right now I think. When I clicked it it gives an error so I changed it a little bit and printed a leaving massage and put a button to redirect to main page.

**Comment by gktpmuhammed** [comment]
Problem solved and pushed to MainApp.
