### ISSUE TITLE
Community page post creating issue without a template

### ISSUE THREAD

**Issue by yunus-topal** [bounswe/2021SpringGroup1#75]
Right now users cannot create a post if there are no templates. Instead, they will get a message like this {}.

We need to replace that with a warning such as "you need a post template first" or "ask your moderators to create a post template!"

**Comment by cemkaya-mpi** [comment]
You can parse the json in the JS callback and check for nonexistent fields. Should be fairly simple. There is an example in one of the html files I've committed to the mainApp branch.

**Comment by MrLebowski42** [comment]
One solution to this would be adding a default template as we discussed before. Maybe that would be more straightforward.

**Comment by gktpmuhammed** [comment]
I solved that prroblem by printing "You need to create a template first!" if returned json is {}. So I think this solved our problem.

**Comment by yunus-topal** [comment]
@gktpmuhammed  solved to problem and we merged his branch into MainApp, problem solved.
