### ISSUE TITLE
Research on Git

### ISSUE THREAD

**Issue by cemkaya-mpi** [bounswe/2021SpringGroup1#8]
Currently, the [page](https://github.com/bounswe/2021SpringGroup1/wiki/Git-Guides) is nearly empty. Does anyone have resources we can put here?

**Comment by yunus-topal** [comment]
Do we need to explain it on that page or links are enough? I put couple links on but im not sure about this.

**Comment by cemkaya-mpi** [comment]
Seems we should add explanations instead of simply adding links.

**Comment by LehabuL** [comment]
I forgot to add the explanations of AlphaPose. It was the last one which didn't have one so the issue is closed.
