### ISSUE TITLE
Adding unit tests

### ISSUE THREAD

**Issue by cemkaya-mpi** [bounswe/2021SpringGroup1#82]
We must add unit tests to the MainApp branch. For this purpose, I have opened the Mainapp-tests branch. Please add your unit tests to this branch.

**Comment by yunus-topal** [comment]
I added some unit tests to test Person creation into mainapp/tests.py and they are working as intended

**Comment by cemkaya-mpi** [comment]
I've also added unit tests regarding the community model. They are also working as intended.

**Comment by gktpmuhammed** [comment]
I added some unit test to test joining and leaving a community. They are working as intended.

**Comment by MrLebowski42** [comment]
I added some unit tests that tests Post and PostTemplate models. They are working as intended but there is an inconsistency issue regarding our database between branches. This should be resolved later on.

**Comment by cemkaya-mpi** [comment]
I'm relabeling this issue, since we added some unit tests and merged the tests branch into the MainApp branch. All further unit test development can continue within that branch.

**Comment by cemkaya-mpi** [comment]
I'm closing this issue, since we have almost reached the assignment deadline.
