### ISSUE TITLE
Adding language datafield for posts using Detect Language API

### ISSUE THREAD

**Issue by emiroztoprak** [bounswe/2021SpringGroup1#83]
When a post is created, I will concatenate all the text related to the post (title, description, text fields), then I will use Detect Language API and get the detected languages. Since it may return multiple languages, I will concatenate the result separated by comma like: "en,tr,fr". Then I will put this result as a text datafield named "Detected languages". I will be working in the branch MainApp-emir, and hopefully I will finish it today. All feedbacks are appreciated.

**Comment by MrLebowski42** [comment]
That would be a good feature. You might need my help as I made some significant changes in createPost html template and mainly wrote createPost and getPost methods. You can contact me if you encounter some problems.

**Comment by emiroztoprak** [comment]
Thanks for the offer, I didn't make any changes to html templates, so I didn't have much difficulty. I only added some code in the createPost method, and I pushed my version in MainApp-emir. I tested it by creating a test post, it seems to be working. I can make a pull request if it works in your environment as well.  
I am closing this issue since I implemented the new feature.
