### ISSUE TITLE
Preparing the documentation for Milestone 2

### ISSUE THREAD

**Issue by MrLebowski42** [bounswe/2021SpringGroup1#85]
We need to start working on the documentations as we are very close to the deadline. I think we should set up a meeting ASAP to discuss documentation and remaining tasks.

**Comment by yunus-topal** [comment]
I think we should make a meeting tomorrow and finish general parts of the documentation. After that, everyone can fill their parts on their own.

**Comment by cemkaya-mpi** [comment]
Let's set a meeting time on one of our communication channels, such as discord, slack or whatsapp.

**Comment by 4teko7** [comment]
We will meet on june 9 to dockerize our project and deploy to EC2 instance. We will also create a security group to make IP of EC2 accessible via HTTP and HTTPS.

**Comment by 4teko7** [comment]
I completed AWS, Docker parts in both "Evaluation of Tools and Processes Used" and  "Code and Deployment of Practice App" parts. Filled Responsibility Matrix, Wrote some other parts. We move forward as a perfect team

**Comment by gktpmuhammed** [comment]
I am closing this issue since we submitted milestone report. Thanks for all your efforts.
