### ISSUE TITLE
Learning Docker to Dockerize the Django App

### ISSUE THREAD

**Issue by 4teko7** [bounswe/2021SpringGroup1#86]
I watched some tutorials to learn how to dockerize our django app.

**Comment by yunus-topal** [comment]
I couldn't attend the ps session but i watched recordings about docker

**Comment by 4teko7** [comment]
I have watched lots of video from Udemy and Youtube. I have also searched how to dockerize a django app from google especially StackOverFlow.

**Comment by emrahdgn** [comment]
I have also watched lots of video from Youtube and Problem Session recordings. I will help you in dockerizing process.

**Comment by MrLebowski42** [comment]
I had attended PS however I need to examine some documentations to understand this process thoroughly.

**Comment by cemkaya-mpi** [comment]
I used docker before, but not for web applications. I will also read the documentations.

**Comment by gktpmuhammed** [comment]
I had attended ps and watched some tutorials about docker.

**Comment by emiroztoprak** [comment]
Sorry for the late comment, I also attended the PS, downloaded Docker for Windows and read the [official tutorial for Docker](https://docs.docker.com/get-started/). Then I ran my first container and deployed it to learn the basics.
