### ISSUE TITLE
Removing Trash Files

### ISSUE THREAD

**Issue by emrahdgn** [bounswe/2021SpringGroup1#96]
Files that should not be  must be removed. We have to dockerize the new version and put it on EC2.

**Comment by elxif** [comment]
Let's push the final versions of our branches and dockerize the new version together.

**Comment by yunus-topal** [comment]
There is post2 directory in practice-app and some tables from post2 in the database that is not used at all. If we carried out every functionality from post2 to mainapp, we can get rid of post2 directory and make new migration to clear useless tables.

**Comment by cemkaya-mpi** [comment]
the same goes for the community directory.

**Comment by MrLebowski42** [comment]
All functions and models in post2 app are outdated and unused by now, we can safely remove them.

**Comment by emrahdgn** [comment]
I realized that for Mac OS users there is trash MAC_OSX folder. I added them to .gitignore file.

**Comment by emrahdgn** [comment]
All trash files are removed. I am closing this issue
