### ISSUE TITLE
Creating RESTful API calls

### ISSUE THREAD

**Issue by cemkaya-mpi** [bounswe/2021SpringGroup1#98]
Hello everyone, we must create RESTful api calls for the mainapp. You can see some examples in the new MainApp-RESTful branch. Please add at least one GET and POST method in this branch ASAP.

**Comment by cemkaya-mpi** [comment]
I've added some api calls for getting a list of communities, creating them and deleting them.

**Comment by yunus-topal** [comment]
I've added createUser and getUserCommunities api calls.

**Comment by cemkaya-mpi** [comment]
I've figured out how do do the unit tests directly in the django framework for these calls. We can do the tests like this in addition to checking our functions with postman. See commit [1f05248](https://github.com/bounswe/2021SpringGroup1/commit/1f05248aeb8c9ec88a7d7ba159221cc3a2f6759e). I've pushed some unit tests for the RESTful api under the CommunityTestCase class.

**Comment by cemkaya-mpi** [comment]
Calls have been created and merged into the MainApp branch. Everything was dockerized and deployed to AWS. The app is accessible [here](http://54.164.7.166:8080/). Closing the issue.
